package utils

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// FrpcTomlConfig 用于生成frpc配置
type FrpcTomlConfig struct {
	ServerAddr string
	ServerPort int
	AuthToken  string
	User       string
	// 在线管理配置
	AdminEnabled    bool
	AdminPort       int    // 本地 webServer 端口
	AdminUser       string
	AdminPass       string
	AdminRemotePort int    // 映射到 frps 的远程端口
	Proxies         []ProxyConfig
	Visitors        []VisitorConfig
}

type VisitorConfig struct {
	Name       string
	Type       string
	ServerName string
	ServerUser string
	SecretKey  string
	BindAddr   string
	BindPort   int
}

type ProxyConfig struct {
	Name        string
	Type        string
	LocalIP     string
	LocalPort   int
	RemotePort  int
	SecretKey   string
	AllowUsers  string

	// 传输选项
	BandwidthLimit     string
	BandwidthLimitMode string
	UseEncryption      bool
	UseCompression     bool

	// 健康检查
	HealthCheckType            string
	HealthCheckTimeoutSeconds  int
	HealthCheckMaxFailed       int
	HealthCheckIntervalSeconds int
	HealthCheckPath            string

	// 插件配置
	PluginType   string
	PluginParams map[string]interface{}

	ExtraConfig map[string]interface{}
}

// GenerateFrpcToml 生成frpc.toml配置文件内容
func GenerateFrpcToml(config FrpcTomlConfig) string {
	var buf bytes.Buffer

	// 基础配置
	buf.WriteString("# FRP Client Configuration\n")
	buf.WriteString("# Generated by frp-admin\n\n")

	if config.User != "" {
		buf.WriteString(fmt.Sprintf("user = \"%s\"\n", config.User))
	}
	buf.WriteString(fmt.Sprintf("serverAddr = \"%s\"\n", config.ServerAddr))
	buf.WriteString(fmt.Sprintf("serverPort = %d\n", config.ServerPort))
	buf.WriteString("\n")

	// 日志配置
	buf.WriteString("log.to = \"/var/log/frpc.log\"\n")
	buf.WriteString("log.level = \"info\"\n")
	buf.WriteString("log.maxDays = 3\n")
	buf.WriteString("\n")

	// 认证配置
	buf.WriteString("auth.method = \"token\"\n")
	buf.WriteString(fmt.Sprintf("auth.token = \"%s\"\n", config.AuthToken))
	buf.WriteString("\n")

	// 连接配置
	buf.WriteString("# 登录失败不退出，持续重试\n")
	buf.WriteString("loginFailExit = false\n")
	buf.WriteString("\n")


	// webServer 配置（用于在线管理）
	if config.AdminEnabled && config.AdminPort > 0 {
		buf.WriteString("# 在线管理配置\n")
		buf.WriteString("webServer.addr = \"127.0.0.1\"\n")
		buf.WriteString(fmt.Sprintf("webServer.port = %d\n", config.AdminPort))
		if config.AdminUser != "" {
			buf.WriteString(fmt.Sprintf("webServer.user = \"%s\"\n", config.AdminUser))
		}
		if config.AdminPass != "" {
			buf.WriteString(fmt.Sprintf("webServer.password = \"%s\"\n", config.AdminPass))
		}
		buf.WriteString("\n")
	}

	// 自动生成 frpc-admin 代理（用于远程管理）
	if config.AdminEnabled && config.AdminPort > 0 && config.AdminRemotePort > 0 {
		buf.WriteString("# 在线管理代理（系统自动生成，请勿删除）\n")
		buf.WriteString("[[proxies]]\n")
		buf.WriteString("name = \"frpc-admin\"\n")
		buf.WriteString("type = \"tcp\"\n")
		buf.WriteString("localIP = \"127.0.0.1\"\n")
		buf.WriteString(fmt.Sprintf("localPort = %d\n", config.AdminPort))
		buf.WriteString(fmt.Sprintf("remotePort = %d\n", config.AdminRemotePort))
		buf.WriteString("\n")
	}

	// 代理配置
	for _, proxy := range config.Proxies {
		buf.WriteString("[[proxies]]\n")
		buf.WriteString(fmt.Sprintf("name = \"%s\"\n", proxy.Name))
		buf.WriteString(fmt.Sprintf("type = \"%s\"\n", proxy.Type))

		// 插件模式下不需要 localIP/localPort
		if proxy.PluginType == "" {
			if proxy.LocalIP != "" {
				buf.WriteString(fmt.Sprintf("localIP = \"%s\"\n", proxy.LocalIP))
			}
			if proxy.LocalPort > 0 {
				buf.WriteString(fmt.Sprintf("localPort = %d\n", proxy.LocalPort))
			}
		}

		switch proxy.Type {
		case "tcp", "udp":
			if proxy.RemotePort >= 0 {
				buf.WriteString(fmt.Sprintf("remotePort = %d\n", proxy.RemotePort))
			}
		case "stcp", "xtcp", "sudp":
			if proxy.SecretKey != "" {
				buf.WriteString(fmt.Sprintf("secretKey = \"%s\"\n", proxy.SecretKey))
			}
			// 处理 allowUsers
			allowUsers := proxy.AllowUsers
			if allowUsers == "" {
				allowUsers = "*"
			}
			if allowUsers == "*" {
				buf.WriteString("allowUsers = [\"*\"]\n")
			} else {
				// 多个用户用逗号分隔，转换为数组格式
				users := strings.Split(allowUsers, ",")
				var quotedUsers []string
				for _, u := range users {
					u = strings.TrimSpace(u)
					if u != "" {
						quotedUsers = append(quotedUsers, fmt.Sprintf("\"%s\"", u))
					}
				}
				buf.WriteString(fmt.Sprintf("allowUsers = [%s]\n", strings.Join(quotedUsers, ", ")))
			}
		}

		// 传输选项
		if proxy.BandwidthLimit != "" {
			buf.WriteString(fmt.Sprintf("transport.bandwidthLimit = \"%s\"\n", proxy.BandwidthLimit))
			if proxy.BandwidthLimitMode != "" {
				buf.WriteString(fmt.Sprintf("transport.bandwidthLimitMode = \"%s\"\n", proxy.BandwidthLimitMode))
			}
		}
		if proxy.UseEncryption {
			buf.WriteString("transport.useEncryption = true\n")
		}
		if proxy.UseCompression {
			buf.WriteString("transport.useCompression = true\n")
		}

		// 健康检查（udp 不支持）
		if proxy.HealthCheckType != "" && proxy.Type != "udp" {
			buf.WriteString(fmt.Sprintf("healthCheck.type = \"%s\"\n", proxy.HealthCheckType))
			if proxy.HealthCheckTimeoutSeconds > 0 {
				buf.WriteString(fmt.Sprintf("healthCheck.timeoutSeconds = %d\n", proxy.HealthCheckTimeoutSeconds))
			}
			if proxy.HealthCheckMaxFailed > 0 {
				buf.WriteString(fmt.Sprintf("healthCheck.maxFailed = %d\n", proxy.HealthCheckMaxFailed))
			}
			if proxy.HealthCheckIntervalSeconds > 0 {
				buf.WriteString(fmt.Sprintf("healthCheck.intervalSeconds = %d\n", proxy.HealthCheckIntervalSeconds))
			}
			if proxy.HealthCheckType == "http" && proxy.HealthCheckPath != "" {
				buf.WriteString(fmt.Sprintf("healthCheck.path = \"%s\"\n", proxy.HealthCheckPath))
			}
		}

		// 插件配置（只有 tcp 支持）
		if proxy.PluginType != "" && proxy.Type == "tcp" {
			buf.WriteString(fmt.Sprintf("[proxies.plugin]\n"))
			buf.WriteString(fmt.Sprintf("type = \"%s\"\n", proxy.PluginType))
			if proxy.PluginParams != nil {
				for k, v := range proxy.PluginParams {
					buf.WriteString(fmt.Sprintf("%s = %s\n", k, formatTomlValue(v)))
				}
			}
		}

		// 额外配置
		if proxy.ExtraConfig != nil {
			for k, v := range proxy.ExtraConfig {
				buf.WriteString(fmt.Sprintf("%s = %s\n", k, formatTomlValue(v)))
			}
		}

		buf.WriteString("\n")
	}

	// 访问者配置
	for _, visitor := range config.Visitors {
		buf.WriteString("[[visitors]]\n")
		buf.WriteString(fmt.Sprintf("name = \"%s\"\n", visitor.Name))
		buf.WriteString(fmt.Sprintf("type = \"%s\"\n", visitor.Type))
		buf.WriteString(fmt.Sprintf("serverName = \"%s\"\n", visitor.ServerName))
		if visitor.ServerUser != "" {
			buf.WriteString(fmt.Sprintf("serverUser = \"%s\"\n", visitor.ServerUser))
		}
		if visitor.SecretKey != "" {
			buf.WriteString(fmt.Sprintf("secretKey = \"%s\"\n", visitor.SecretKey))
		}
		if visitor.BindAddr != "" {
			buf.WriteString(fmt.Sprintf("bindAddr = \"%s\"\n", visitor.BindAddr))
		}
		if visitor.BindPort > 0 {
			buf.WriteString(fmt.Sprintf("bindPort = %d\n", visitor.BindPort))
		}
		buf.WriteString("\n")
	}

	return buf.String()
}

func formatTomlValue(v interface{}) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("\"%s\"", val)
	case bool:
		return fmt.Sprintf("%t", val)
	case float64:
		if val == float64(int(val)) {
			return fmt.Sprintf("%d", int(val))
		}
		return fmt.Sprintf("%f", val)
	case int:
		return fmt.Sprintf("%d", val)
	default:
		jsonBytes, _ := json.Marshal(val)
		return string(jsonBytes)
	}
}

// ParseFrpsConfig 解析frps.toml配置文件，提取关键信息
type FrpsConfigInfo struct {
	BindAddr       string `json:"bind_addr"`
	BindPort       int    `json:"bind_port"`
	AuthToken      string `json:"auth_token"`
	WebServerAddr  string `json:"web_server_addr"`
	WebServerPort  int    `json:"web_server_port"`
	WebServerUser  string `json:"web_server_user"`
	WebServerPass  string `json:"web_server_pass"`
	VhostHTTPPort  int    `json:"vhost_http_port"`
	VhostHTTPSPort int    `json:"vhost_https_port"`
	SubdomainHost  string `json:"subdomain_host"`
}
